import type { EngineSelection, RuleDefinition, RuleId } from '@cqa/shared';

/** Phase 1 rule definitions. Must stay consistent with docs/QA_RULE_CATALOG.md. */
export const PHASE1_RULES: readonly RuleDefinition[] = [
  {
    id: 'RUN-001',
    name: 'Initial page loads',
    category: 'runtime',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'critical',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every URL target',
    evidenceCollected: ['Final sanitized URL', 'HTTP status', 'Screenshot', 'Navigation timing'],
    limitations: ['A successful response does not prove the page is the correct course page.'],
    standards: [],
  },
  {
    id: 'RUN-002',
    name: 'Uncaught JavaScript exceptions',
    category: 'runtime',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Exception message', 'Sanitized stack'],
    limitations: ['Impact on the learner is not determined; third-party scripts are included.'],
    standards: [],
  },
  {
    id: 'RUN-003',
    name: 'Console errors',
    category: 'runtime',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Console text (sanitized)', 'Source location'],
    limitations: ['Many console errors are benign.'],
    standards: [],
  },
  {
    id: 'RUN-004',
    name: 'Failed subrequests',
    category: 'runtime',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Sanitized URL', 'Resource type', 'Status or network error'],
    limitations: ['Requests blocked by the scan policy are reported as NET-002, not as course defects.'],
    standards: [],
  },
  {
    id: 'RUN-005',
    name: 'Page title present',
    category: 'runtime',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Top document',
    evidenceCollected: ['Title text'],
    limitations: ['Title adequacy needs manual review.'],
    standards: [{ standard: 'WCAG', version: '2.2', criterion: '2.4.2', relation: 'relevant' }],
  },
  {
    id: 'RUN-006',
    name: 'Navigation timing captured',
    category: 'performance',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'informational',
    defaultConfidence: 'medium',
    capability: 'implemented',
    phase: 1,
    applicability: 'Top document',
    evidenceCollected: ['Navigation Timing entry'],
    limitations: ['Single sample; depends on machine, network, and cache.'],
    standards: [],
  },
  {
    id: 'NET-002',
    name: 'Subrequest blocked by policy',
    category: 'network',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Sanitized URL', 'Block reason'],
    limitations: ['Blocked content may hide course behavior; reported as a coverage gap.'],
    standards: [],
  },
  {
    id: 'NET-003',
    name: 'Redirect leaves allowed scope',
    category: 'network',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Initial navigation',
    evidenceCollected: ['Redirect chain'],
    limitations: [],
    standards: [],
  },
];

const rule = (r: Omit<RuleDefinition, 'capability' | 'standards'> & Partial<Pick<RuleDefinition, 'capability' | 'standards'>>): RuleDefinition => ({
  capability: 'implemented',
  standards: [],
  ...r,
});

/** Phase 2a: traversal and coverage rules. */
export const TRAVERSAL_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'NAV-001',
    name: 'Recognized control produces its expected result',
    category: 'navigation',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Tabs, accordions, and dialog openers the adapter recognizes and defines a result for',
    evidenceCollected: ['Action path', 'Expected and observed result', 'Screenshot after the action'],
    limitations: ['Only for controls whose expected result the adapter defines; other no-change clicks are NAV-002.'],
  }),
  rule({
    id: 'NAV-002',
    name: 'Action produced no observable change',
    category: 'navigation',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'low',
    defaultConfidence: 'low',
    phase: 2,
    applicability: 'Attempted actions without a defined expected result (for example Next/Back)',
    evidenceCollected: ['Action path', 'State signature before and after'],
    limitations: ['Inconclusive: the control may be gated, already at the end, or rely on behavior the scanner cannot observe.'],
  }),
  rule({
    id: 'NAV-003',
    name: 'Dialog can be closed',
    category: 'navigation',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Open dialogs with a recognized close control',
    evidenceCollected: ['Action path', 'Dialog visibility after the close action'],
    limitations: ['Requires a recognizable close control (Close, Dismiss, ×, OK, Done, Cancel).'],
  }),
  rule({
    id: 'COV-001',
    name: 'Unsafe or ambiguous action skipped',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Controls discovered in reached states',
    evidenceCollected: ['Control description', 'Skip reason'],
    limitations: ['Skipped controls and anything behind them are unverified.'],
  }),
  rule({
    id: 'COV-002',
    name: 'Frame not inspected',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Frames in reached states',
    evidenceCollected: ['Frame URL (sanitized)', 'Reason'],
    limitations: ['Content inside the frame is unverified.'],
  }),
  rule({
    id: 'COV-003',
    name: 'Canvas or unsupported rendering surface',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Reached states',
    evidenceCollected: ['Canvas size and position'],
    limitations: ['DOM-based checks cannot inspect canvas-rendered content (for example parts of Storyline).'],
  }),
  rule({
    id: 'COV-004',
    name: 'Scan budget reached',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Each run with traversal enabled',
    evidenceCollected: ['Budget', 'Counts when it was reached'],
    limitations: ['States beyond the budget are unverified.'],
  }),
];

/** Phase 2b: link checks. */
export const LINK_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'LNK-001',
    name: 'Link returns an HTTP error',
    category: 'links',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'HTTP(S) links in reached states',
    evidenceCollected: ['Normalized URL', 'Method', 'Status', 'Redirect chain', 'Where the link appears'],
    limitations: ['5xx responses are retried once and may still be transient.', 'A successful response does not prove the destination is correct (LNK-004, manual).'],
  }),
  rule({
    id: 'LNK-002',
    name: 'Link destination is access-restricted',
    category: 'links',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Links answering 401, 403, or 407',
    evidenceCollected: ['Status'],
    limitations: ['Not a broken link: the destination may work for signed-in learners.'],
  }),
  rule({
    id: 'LNK-003',
    name: 'Link could not be verified',
    category: 'links',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Links that time out, fail DNS or connection, hit rate limits, or are blocked by the scan policy',
    evidenceCollected: ['Error'],
    limitations: ['Not a broken link: the destination was not verified either way.'],
  }),
  rule({
    id: 'LNK-005',
    name: 'Malformed, empty, or script link',
    category: 'links',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Anchors with href in reached states',
    evidenceCollected: ['href', 'Link text'],
    limitations: ['javascript: links may work, but are fragile and often inaccessible.'],
  }),
];

/** Phase 2b: images and media. */
export const MEDIA_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'MED-001',
    name: 'Broken image',
    category: 'media',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Rendered <img> elements after scrolling into view',
    evidenceCollected: ['Image source', 'Alt text', 'Load state and natural size', 'Where it appears'],
    limitations: ['CSS background images are not checked.', 'Images still loading after the wait are not tested, not passed.'],
  }),
  rule({
    id: 'MED-002',
    name: 'Audio or video failed to load',
    category: 'media',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    phase: 2,
    applicability: '<audio> and <video> elements',
    evidenceCollected: ['MediaError code', 'Source', 'Network state'],
    limitations: ['Loading metadata does not prove playback works end to end. Embedded players (YouTube, Vimeo, Storyline) are not inspected.'],
  }),
  rule({
    id: 'MED-003',
    name: 'Video has no caption or subtitle track',
    category: 'media',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: '<video> elements',
    evidenceCollected: ['Text track list'],
    limitations: ['Captions may be burned in or provided by a custom player. Caption accuracy is manual review.'],
    standards: [{ standard: 'WCAG', version: '2.2', criterion: '1.2.2', relation: 'relevant' }],
  }),
  rule({
    id: 'MED-004',
    name: 'Media without native controls',
    category: 'media',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'low',
    phase: 2,
    applicability: '<audio> and <video> elements that autoplay or have no controls attribute',
    evidenceCollected: ['controls / autoplay / muted attributes'],
    limitations: ['Custom players often provide their own controls.'],
    capability: 'heuristic',
  }),
  rule({
    id: 'MED-005',
    name: 'Asset larger than the size threshold',
    category: 'media',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Images and media whose transfer size the browser exposes',
    evidenceCollected: ['Encoded size', 'Threshold and its source'],
    limitations: ['Cross-origin assets without Timing-Allow-Origin report no size and are not tested.', 'Thresholds are defaults, not a standard.'],
  }),
];

/** Phase 2b: rule-based text checks. Not a grammar review. */
export const TEXT_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'TXT-001',
    name: 'Placeholder or production note in visible text',
    category: 'content',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Visible text in reached states',
    evidenceCollected: ['Matched text and surrounding words', 'Element'],
    limitations: ['Pattern-based; exclusions handle intentional uses. Text inside canvas or unreached states is not checked.'],
  }),
  rule({
    id: 'TXT-002',
    name: 'Terminology rule',
    category: 'content',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Visible text, when a terminology list is configured',
    evidenceCollected: ['Term', 'Preferred term', 'Context'],
    limitations: ['Context-dependent; no grammar or style review is claimed.'],
  }),
];

/**
 * Phase 3: accessibility. Individual axe-core rules are reported as
 * `A11Y-AXE-<axe rule id>` and defined on demand (see `axeRuleDefinition`).
 * WCAG criteria, severity, and tags come from axe's own metadata.
 */
export const ACCESSIBILITY_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'A11Y-ENG',
    name: 'Automated accessibility engine ran on this state',
    category: 'accessibility',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 3,
    applicability: 'Every reached state',
    evidenceCollected: ['axe-core version', 'Rules evaluated'],
    limitations: ['Records that axe-core ran, not that the state is accessible. Automated rules cover a subset of WCAG; frames axe could not reach are reported by its frame-tested rule.'],
  }),
  rule({
    id: 'A11Y-008',
    name: 'Content reflows at 320 CSS pixels without horizontal scrolling',
    category: 'accessibility',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'low',
    capability: 'heuristic',
    phase: 3,
    applicability: 'Every reached state',
    evidenceCollected: ['Scroll width at 320 px', 'Overflowing elements'],
    limitations: ['Viewport simulation only; no zoom. Content that legitimately needs two-dimensional scrolling (maps, data tables) is allowed by the criterion.', 'Fixed-size stages (for example Storyline) usually scale rather than reflow and may be flagged.'],
    standards: [{ standard: 'WCAG', criterion: '1.4.10', relation: 'relevant' }],
  }),
];

/** Phase 3: bounded keyboard journeys. */
export const KEYBOARD_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'KBD-001',
    name: 'No keyboard trap while tabbing',
    category: 'keyboard',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'medium',
    phase: 3,
    applicability: 'Reached states without an open modal dialog',
    evidenceCollected: ['Focus sequence', 'Confirmation attempt (Escape, further Tab presses)'],
    limitations: ['Bounded: at most 60 Tab presses per state. Only reports a trap that survives Escape and further Tab presses.'],
    standards: [{ standard: 'WCAG', criterion: '2.1.2', relation: 'relevant' }],
  }),
  rule({
    id: 'KBD-002',
    name: 'Focus indicator is visible',
    category: 'keyboard',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 3,
    applicability: 'Elements that receive focus during the Tab journey',
    evidenceCollected: ['Computed style of the element focused and unfocused'],
    limitations: ['Compares computed outline, shadow, border, background, color, and text decoration; it does not look at pixels, so subtle or low-contrast indicators need manual review.'],
    standards: [{ standard: 'WCAG', criterion: '2.4.7', relation: 'relevant' }],
  }),
  rule({
    id: 'KBD-003',
    name: 'Dialog moves focus in, keeps it in (when modal), and returns it on close',
    category: 'keyboard',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 3,
    applicability: 'Recognized dialogs opened from a control',
    evidenceCollected: ['Active element after opening', 'Focus sequence while open', 'Active element after closing'],
    limitations: ['Escape is not required of every popup; closing uses the dialog’s own close control. Containment is checked only for aria-modal dialogs.', 'At most 12 keyboard activations per scan.'],
  }),
  rule({
    id: 'KBD-004',
    name: 'Recognized controls can be reached and operated by keyboard',
    category: 'keyboard',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'medium',
    phase: 3,
    applicability: 'Tabs, expandable sections, and dialog openers whose mouse activation worked',
    evidenceCollected: ['Focusability', 'Result of pressing Enter or Space'],
    limitations: ['Only controls the generic adapter recognizes and that worked with the mouse; at most 12 keyboard activations per scan.'],
    standards: [{ standard: 'WCAG', criterion: '2.1.1', relation: 'relevant' }],
  }),
];

/** Phase 4: responsive layout, visual heuristics, performance evidence, and baselines. All geometry rules are heuristics. */
export const LAYOUT_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'LAY-001',
    name: 'No unintended horizontal page overflow',
    category: 'layout',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 4,
    applicability: 'Each reached screen at each tested viewport',
    evidenceCollected: ['Document scroll width vs viewport width', 'Elements extending past the edge, with bounds'],
    limitations: ['Elements inside intentional scroll containers, carousels, and fixed overlays are excluded.', 'A viewport simulation, not a real device.'],
  }),
  rule({
    id: 'LAY-002',
    name: 'No text clipped by its container',
    category: 'layout',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'low',
    capability: 'heuristic',
    phase: 4,
    applicability: 'Elements with text and overflow hidden or clipped',
    evidenceCollected: ['Content size vs visible size', 'Element bounds', 'Outlined screenshot'],
    limitations: ['Ellipsis truncation and line clamping are treated as intentional and not reported.', 'Hidden text revealed by interaction is not measured.'],
  }),
  rule({
    id: 'LAY-003',
    name: 'Controls are not covered by another element',
    category: 'layout',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'low',
    capability: 'heuristic',
    phase: 4,
    applicability: 'Visible controls inside the viewport',
    evidenceCollected: ['Control and the element at its center point', 'Bounds'],
    limitations: ["Only a control's center point is tested. Controls behind an open modal dialog, and covering by a control's own parts, are excluded. Controls below the fold are not tested."],
  }),
  rule({
    id: 'LAY-004',
    name: 'Dialogs fit inside the viewport',
    category: 'layout',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 4,
    applicability: 'Open dialogs',
    evidenceCollected: ['Dialog bounds vs viewport'],
    limitations: ['A dialog taller than the viewport that scrolls inside itself is not reported.'],
  }),
  rule({
    id: 'LAY-005',
    name: 'Web fonts load',
    category: 'layout',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    phase: 4,
    applicability: 'Every reached screen',
    evidenceCollected: ['Font family and load status'],
    limitations: ['Only fonts the page tried to use are reported.'],
  }),
  rule({
    id: 'PERF-001',
    name: 'Page-load evidence is within thresholds',
    category: 'performance',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 4,
    applicability: 'The first page, at the primary viewport',
    evidenceCollected: ['Load time', 'Transferred bytes (where the browser exposes them)', 'Request count', 'Largest assets', 'Test conditions'],
    limitations: ['Not a performance audit. One cold-cache sample from this machine and network; cross-origin resources without Timing-Allow-Origin report no size and are listed as unavailable.'],
  }),
  rule({
    id: 'VIS-001',
    name: 'Screenshot matches the stored baseline',
    category: 'visual',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'medium',
    phase: 4,
    applicability: 'Only when comparing against a baseline recorded with identical course, screen, viewport, browser, and settings',
    evidenceCollected: ['Baseline and current screenshots', 'Diff image', 'Fraction of differing pixels'],
    limitations: ['A difference is a review signal, never proof of a defect. Animations, carousels, dates, and ads cause differences. Different settings are never compared.'],
  }),
];

/** Brand checks. They run only when a client profile supplies brand values; there are no built-in brand rules. */
export const BRAND_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'BRD-001',
    name: 'Text uses an approved font',
    category: 'brand',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 5,
    applicability: 'Profiles with approved fonts; visible text on each reached screen',
    evidenceCollected: ['Computed font family of visible text', 'Sample text and element'],
    limitations: ['Compares the first font in the computed list by name; a fallback font actually drawn is not detected.', 'Icon fonts are skipped by name.', 'The approved list is whatever the client profile says; the scanner does not know the brand rules.'],
  }),
  rule({
    id: 'BRD-002',
    name: 'Text colour is close to an approved colour',
    category: 'brand',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'low',
    capability: 'heuristic',
    phase: 5,
    applicability: 'Profiles with approved colours; visible text on each reached screen',
    evidenceCollected: ['Computed text colour', 'Nearest approved colour and CIEDE2000 distance', 'Sample element'],
    limitations: ['Black and white text is treated as neutral and not flagged unless approved colours exclude it.', 'Only text colour is compared, not backgrounds, images, or gradients.'],
  }),
  rule({
    id: 'BRD-003',
    name: 'Text is not smaller than the minimum size',
    category: 'brand',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 5,
    applicability: 'Profiles with a minimum text size; visible text on each reached screen',
    evidenceCollected: ['Computed font size in CSS pixels', 'Sample text and element'],
    limitations: ['Measured at the screen size being tested; text scaled by a fixed-size stage is measured before scaling.'],
  }),
];

/** Static package inspection (Phase 6). Run once at upload; no course code is executed. */
export const PACKAGE_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'PKG-001',
    name: 'Archive accepted',
    category: 'package',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'critical',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 6,
    applicability: 'Every uploaded ZIP',
    evidenceCollected: ["Entry list","Size, ratio, and path checks"],
    limitations: ["A rejected archive is never extracted, so nothing inside it was inspected."],
  }),
  rule({
    id: 'PKG-002',
    name: 'Manifest is well-formed XML',
    category: 'package',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 6,
    applicability: 'Packages with imsmanifest.xml',
    evidenceCollected: ["XML parser error and line"],
    limitations: ["Well-formed is not schema-valid; the SCORM schemas are not checked."],
  }),
  rule({
    id: 'PKG-003',
    name: 'SCORM version declared',
    category: 'package',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'implemented',
    phase: 6,
    applicability: 'Packages with imsmanifest.xml',
    evidenceCollected: ["Declared schema version","Namespaces used"],
    limitations: ["A declared version does not prove runtime behaviour."],
  }),
  rule({
    id: 'PKG-004',
    name: 'Launch file resolves',
    category: 'package',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'critical',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 6,
    applicability: 'Packages with a manifest, or HTML5 packages',
    evidenceCollected: ["Resolved launch path (xml:base applied)"],
    limitations: ["A file that exists may still fail to run."],
  }),
  rule({
    id: 'PKG-005',
    name: 'Referenced local files exist with matching letter case',
    category: 'package',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'medium',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 6,
    applicability: 'Manifest and HTML pages',
    evidenceCollected: ["Missing or case-mismatched paths"],
    limitations: ["Only plain src/href attributes in HTML are followed; paths built in script are not."],
  }),
  rule({
    id: 'PKG-006',
    name: 'Outside web dependencies',
    category: 'package',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'heuristic',
    phase: 6,
    applicability: 'Text files in the package',
    evidenceCollected: ["Hosts and sample addresses found"],
    limitations: ["Static text search; addresses built at run time are not found."],
  }),
  rule({
    id: 'PKG-007',
    name: 'Scan selection is disclosed',
    category: 'package',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 6,
    applicability: 'Packages with several lessons, organizations, or HTML files',
    evidenceCollected: ["Which launch points were and were not scanned"],
    limitations: ["Sequencing rules in the manifest are not evaluated."],
  }),
];

export const ALL_RULES: readonly RuleDefinition[] = [
  ...PHASE1_RULES,
  ...TRAVERSAL_RULES,
  ...LINK_RULES,
  ...MEDIA_RULES,
  ...TEXT_RULES,
  ...ACCESSIBILITY_RULES,
  ...KEYBOARD_RULES,
  ...LAYOUT_RULES,
  ...BRAND_RULES,
  ...PACKAGE_RULES,
];

const BY_ID = new Map(ALL_RULES.map((r) => [r.id, r]));

const AXE_IMPACT_SEVERITY = { critical: 'critical', serious: 'high', moderate: 'medium', minor: 'low' } as const;

/** Severity for an axe impact. Repeatable mapping documented in docs/QA_RULE_CATALOG.md. */
export function severityForAxeImpact(impact: string | null | undefined): RuleDefinition['defaultSeverity'] {
  return AXE_IMPACT_SEVERITY[impact as keyof typeof AXE_IMPACT_SEVERITY] ?? 'medium';
}

/** WCAG success criteria from axe tags such as `wcag111` or `wcag1410`. */
export function wcagCriteriaFromTags(tags: readonly string[]): string[] {
  const out: string[] = [];
  for (const t of tags) {
    const m = /^wcag(\d)(\d)(\d+)$/.exec(t);
    if (m) out.push(`${m[1]}.${m[2]}.${m[3]}`);
  }
  return out;
}

/** Definition for one axe-core rule, built from axe's own metadata. */
export function axeRuleDefinition(axeRuleId: string, meta: { help?: string; impact?: string | null; tags?: readonly string[] } = {}): RuleDefinition {
  const tags = meta.tags ?? [];
  const wcag = wcagCriteriaFromTags(tags);
  return {
    id: `A11Y-AXE-${axeRuleId}`,
    name: meta.help ?? axeRuleId,
    category: 'accessibility',
    defaultFindingType: wcag.length || tags.some((t) => t.startsWith('wcag')) ? 'standards_warning' : 'heuristic_warning',
    defaultSeverity: severityForAxeImpact(meta.impact),
    defaultConfidence: wcag.length ? 'high' : 'medium',
    capability: 'implemented',
    phase: 3,
    applicability: 'Every reached state and frame axe-core can reach',
    evidenceCollected: ['axe-core version', 'Rule ID', 'Impact', 'Affected nodes', 'Standard tags'],
    limitations: ['Automated rules cover a subset of WCAG; passing rules do not establish compliance. Untested frames and surfaces are not counted as passed.'],
    standards: wcag.map((criterion) => ({ standard: 'WCAG' as const, criterion, relation: 'relevant' as const })),
    engineRuleId: axeRuleId,
  };
}

export function getRule(id: RuleId): RuleDefinition {
  const found = BY_ID.get(id);
  if (found) return found;
  if (id.startsWith('A11Y-AXE-')) return axeRuleDefinition(id.slice('A11Y-AXE-'.length));
  throw new Error(`Unknown rule ${id}`);
}

export function allRules(): readonly RuleDefinition[] {
  return ALL_RULES;
}

/** Rules a run owns given its engine selection; each must end with a result or a reason. */
export function rulesForEngines(engines: EngineSelection): readonly RuleDefinition[] {
  return [
    ...PHASE1_RULES,
    ...(engines.traversal ? TRAVERSAL_RULES : []),
    ...(engines.links ? LINK_RULES : []),
    ...(engines.media ? MEDIA_RULES : []),
    ...(engines.content ? TEXT_RULES : []),
    ...(engines.accessibility ? ACCESSIBILITY_RULES : []),
    ...(engines.keyboard ? KEYBOARD_RULES : []),
    ...(engines.layout ? LAYOUT_RULES.filter((r) => r.id.startsWith('LAY-')) : []),
    ...(engines.performance ? LAYOUT_RULES.filter((r) => r.id === 'PERF-001') : []),
    ...(engines.visualBaseline ? LAYOUT_RULES.filter((r) => r.id === 'VIS-001') : []),
    ...(engines.brand ? BRAND_RULES : []),
  ];
}
