import type { EngineSelection, RuleDefinition, RuleId } from '@cqa/shared';

/** Phase 1 rule definitions. Must stay consistent with docs/QA_RULE_CATALOG.md. */
export const PHASE1_RULES: readonly RuleDefinition[] = [
  {
    id: 'RUN-001',
    name: 'Initial page loads',
    category: 'runtime',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'critical',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every URL target',
    evidenceCollected: ['Final sanitized URL', 'HTTP status', 'Screenshot', 'Navigation timing'],
    limitations: ['A successful response does not prove the page is the correct course page.'],
    standards: [],
  },
  {
    id: 'RUN-002',
    name: 'Uncaught JavaScript exceptions',
    category: 'runtime',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Exception message', 'Sanitized stack'],
    limitations: ['Impact on the learner is not determined; third-party scripts are included.'],
    standards: [],
  },
  {
    id: 'RUN-003',
    name: 'Console errors',
    category: 'runtime',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Console text (sanitized)', 'Source location'],
    limitations: ['Many console errors are benign.'],
    standards: [],
  },
  {
    id: 'RUN-004',
    name: 'Failed subrequests',
    category: 'runtime',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Sanitized URL', 'Resource type', 'Status or network error'],
    limitations: ['Requests blocked by the scan policy are reported as NET-002, not as course defects.'],
    standards: [],
  },
  {
    id: 'RUN-005',
    name: 'Page title present',
    category: 'runtime',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Top document',
    evidenceCollected: ['Title text'],
    limitations: ['Title adequacy needs manual review.'],
    standards: [{ standard: 'WCAG', version: '2.2', criterion: '2.4.2', relation: 'relevant' }],
  },
  {
    id: 'RUN-006',
    name: 'Navigation timing captured',
    category: 'performance',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'informational',
    defaultConfidence: 'medium',
    capability: 'implemented',
    phase: 1,
    applicability: 'Top document',
    evidenceCollected: ['Navigation Timing entry'],
    limitations: ['Single sample; depends on machine, network, and cache.'],
    standards: [],
  },
  {
    id: 'NET-002',
    name: 'Subrequest blocked by policy',
    category: 'network',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Every captured state',
    evidenceCollected: ['Sanitized URL', 'Block reason'],
    limitations: ['Blocked content may hide course behavior; reported as a coverage gap.'],
    standards: [],
  },
  {
    id: 'NET-003',
    name: 'Redirect leaves allowed scope',
    category: 'network',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    capability: 'implemented',
    phase: 1,
    applicability: 'Initial navigation',
    evidenceCollected: ['Redirect chain'],
    limitations: [],
    standards: [],
  },
];

const rule = (r: Omit<RuleDefinition, 'capability' | 'standards'> & Partial<Pick<RuleDefinition, 'capability' | 'standards'>>): RuleDefinition => ({
  capability: 'implemented',
  standards: [],
  ...r,
});

/** Phase 2a: traversal and coverage rules. */
export const TRAVERSAL_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'NAV-001',
    name: 'Recognized control produces its expected result',
    category: 'navigation',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Tabs, accordions, and dialog openers the adapter recognizes and defines a result for',
    evidenceCollected: ['Action path', 'Expected and observed result', 'Screenshot after the action'],
    limitations: ['Only for controls whose expected result the adapter defines; other no-change clicks are NAV-002.'],
  }),
  rule({
    id: 'NAV-002',
    name: 'Action produced no observable change',
    category: 'navigation',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'low',
    defaultConfidence: 'low',
    phase: 2,
    applicability: 'Attempted actions without a defined expected result (for example Next/Back)',
    evidenceCollected: ['Action path', 'State signature before and after'],
    limitations: ['Inconclusive: the control may be gated, already at the end, or rely on behavior the scanner cannot observe.'],
  }),
  rule({
    id: 'NAV-003',
    name: 'Dialog can be closed',
    category: 'navigation',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Open dialogs with a recognized close control',
    evidenceCollected: ['Action path', 'Dialog visibility after the close action'],
    limitations: ['Requires a recognizable close control (Close, Dismiss, ×, OK, Done, Cancel).'],
  }),
  rule({
    id: 'COV-001',
    name: 'Unsafe or ambiguous action skipped',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Controls discovered in reached states',
    evidenceCollected: ['Control description', 'Skip reason'],
    limitations: ['Skipped controls and anything behind them are unverified.'],
  }),
  rule({
    id: 'COV-002',
    name: 'Frame not inspected',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Frames in reached states',
    evidenceCollected: ['Frame URL (sanitized)', 'Reason'],
    limitations: ['Content inside the frame is unverified.'],
  }),
  rule({
    id: 'COV-003',
    name: 'Canvas or unsupported rendering surface',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Reached states',
    evidenceCollected: ['Canvas size and position'],
    limitations: ['DOM-based checks cannot inspect canvas-rendered content (for example parts of Storyline).'],
  }),
  rule({
    id: 'COV-004',
    name: 'Scan budget reached',
    category: 'coverage',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Each run with traversal enabled',
    evidenceCollected: ['Budget', 'Counts when it was reached'],
    limitations: ['States beyond the budget are unverified.'],
  }),
];

/** Phase 2b: link checks. */
export const LINK_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'LNK-001',
    name: 'Link returns an HTTP error',
    category: 'links',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'HTTP(S) links in reached states',
    evidenceCollected: ['Normalized URL', 'Method', 'Status', 'Redirect chain', 'Where the link appears'],
    limitations: ['5xx responses are retried once and may still be transient.', 'A successful response does not prove the destination is correct (LNK-004, manual).'],
  }),
  rule({
    id: 'LNK-002',
    name: 'Link destination is access-restricted',
    category: 'links',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Links answering 401, 403, or 407',
    evidenceCollected: ['Status'],
    limitations: ['Not a broken link: the destination may work for signed-in learners.'],
  }),
  rule({
    id: 'LNK-003',
    name: 'Link could not be verified',
    category: 'links',
    defaultFindingType: 'manual_review',
    defaultSeverity: 'informational',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Links that time out, fail DNS or connection, hit rate limits, or are blocked by the scan policy',
    evidenceCollected: ['Error'],
    limitations: ['Not a broken link: the destination was not verified either way.'],
  }),
  rule({
    id: 'LNK-005',
    name: 'Malformed, empty, or script link',
    category: 'links',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Anchors with href in reached states',
    evidenceCollected: ['href', 'Link text'],
    limitations: ['javascript: links may work, but are fragile and often inaccessible.'],
  }),
];

/** Phase 2b: images and media. */
export const MEDIA_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'MED-001',
    name: 'Broken image',
    category: 'media',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Rendered <img> elements after scrolling into view',
    evidenceCollected: ['Image source', 'Alt text', 'Load state and natural size', 'Where it appears'],
    limitations: ['CSS background images are not checked.', 'Images still loading after the wait are not tested, not passed.'],
  }),
  rule({
    id: 'MED-002',
    name: 'Audio or video failed to load',
    category: 'media',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'high',
    defaultConfidence: 'high',
    phase: 2,
    applicability: '<audio> and <video> elements',
    evidenceCollected: ['MediaError code', 'Source', 'Network state'],
    limitations: ['Loading metadata does not prove playback works end to end. Embedded players (YouTube, Vimeo, Storyline) are not inspected.'],
  }),
  rule({
    id: 'MED-003',
    name: 'Video has no caption or subtitle track',
    category: 'media',
    defaultFindingType: 'standards_warning',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: '<video> elements',
    evidenceCollected: ['Text track list'],
    limitations: ['Captions may be burned in or provided by a custom player. Caption accuracy is manual review.'],
    standards: [{ standard: 'WCAG', version: '2.2', criterion: '1.2.2', relation: 'relevant' }],
  }),
  rule({
    id: 'MED-004',
    name: 'Media without native controls',
    category: 'media',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'low',
    phase: 2,
    applicability: '<audio> and <video> elements that autoplay or have no controls attribute',
    evidenceCollected: ['controls / autoplay / muted attributes'],
    limitations: ['Custom players often provide their own controls.'],
    capability: 'heuristic',
  }),
  rule({
    id: 'MED-005',
    name: 'Asset larger than the size threshold',
    category: 'media',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'high',
    phase: 2,
    applicability: 'Images and media whose transfer size the browser exposes',
    evidenceCollected: ['Encoded size', 'Threshold and its source'],
    limitations: ['Cross-origin assets without Timing-Allow-Origin report no size and are not tested.', 'Thresholds are defaults, not a standard.'],
  }),
];

/** Phase 2b: rule-based text checks. Not a grammar review. */
export const TEXT_RULES: readonly RuleDefinition[] = [
  rule({
    id: 'TXT-001',
    name: 'Placeholder or production note in visible text',
    category: 'content',
    defaultFindingType: 'automated_defect',
    defaultSeverity: 'medium',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Visible text in reached states',
    evidenceCollected: ['Matched text and surrounding words', 'Element'],
    limitations: ['Pattern-based; exclusions handle intentional uses. Text inside canvas or unreached states is not checked.'],
  }),
  rule({
    id: 'TXT-002',
    name: 'Terminology rule',
    category: 'content',
    defaultFindingType: 'heuristic_warning',
    defaultSeverity: 'low',
    defaultConfidence: 'medium',
    phase: 2,
    applicability: 'Visible text, when a terminology list is configured',
    evidenceCollected: ['Term', 'Preferred term', 'Context'],
    limitations: ['Context-dependent; no grammar or style review is claimed.'],
  }),
];

export const ALL_RULES: readonly RuleDefinition[] = [...PHASE1_RULES, ...TRAVERSAL_RULES, ...LINK_RULES, ...MEDIA_RULES, ...TEXT_RULES];

const BY_ID = new Map(ALL_RULES.map((r) => [r.id, r]));

export function getRule(id: RuleId): RuleDefinition {
  const found = BY_ID.get(id);
  if (!found) throw new Error(`Unknown rule ${id}`);
  return found;
}

export function allRules(): readonly RuleDefinition[] {
  return ALL_RULES;
}

/** Rules a run owns given its engine selection; each must end with a result or a reason. */
export function rulesForEngines(engines: EngineSelection): readonly RuleDefinition[] {
  return [
    ...PHASE1_RULES,
    ...(engines.traversal ? TRAVERSAL_RULES : []),
    ...(engines.links ? LINK_RULES : []),
    ...(engines.media ? MEDIA_RULES : []),
    ...(engines.content ? TEXT_RULES : []),
  ];
}
